apiVersion: v1
kind: Service
metadata:
  name: rest-service-de3d7ca2-c067-4881-8cd4-4688ffd4e1dc
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: rest-app-de3d7ca2-c067-4881-8cd4-4688ffd4e1dc
spec:
  selector:
    app: rest-app-de3d7ca2-c067-4881-8cd4-4688ffd4e1dc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

