apiVersion: v1
kind: Service
metadata:
  name: rest-service-28fe4287-5ebc-4d88-849a-3cc27bd070d5
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: rest-app-28fe4287-5ebc-4d88-849a-3cc27bd070d5
spec:
  selector:
    app: rest-app-28fe4287-5ebc-4d88-849a-3cc27bd070d5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

